
### Lista de Carros
GET  http://localhost:5191/api/carros


### Buscar Carro pelo ID
GET  http://localhost:5191/api/carros/1

### Cadastrar Carro
POST http://localhost:5191/api/carros
Content-Type: application/json

{
    "name": "Fusca 1956",
    "modelo": {
        "id": 1
    }
}

### Atualiza os dados do Carro
PUT http://localhost:5191/api/carros/1
Content-Type: application/json

{
    "name": "Honda Civic"
}

### Remove Carro pelo ID
DELETE  http://localhost:5191/api/carros/1